### ISSUE TITLE
[Feature Request] Add more colors.

### ISSUE THREAD

**Issue by dingdang66686** [scratch-er/fcitx5-breeze#1]

**Comment by scratch-er** [comment]
在fcitx5主题里面，颜色是写死在图片里的，所以灵活地更改颜色并不容易。不过我也正在考虑一些解决方案，例如以svg而非xcf作为源格式。

**Comment by dingdang66686** [comment]
可以参照一下fcitx5-material-color的解决方案？https://github.com/hosxy/Fcitx5-Material-Color

**Comment by scratch-er** [comment]
> 可以参照一下fcitx5-material-color的解决方案？https://github.com/hosxy/Fcitx5-Material-Color

fcitx5-material-color是一个极其简陋的主题。它所做的几乎就只是用fcitx5自身的特性绘制出方框作为背景和候选词高亮的颜色。这样固然方便，带来的一个严重问题就是很难做出生动的细节。我认为这种方案对于fcitx5-breeze主题是不适用的。

**Comment by scratch-er** [comment]
我目前正在考虑制作一套可以自动生成主题变种的脚本，它所做的无非是替换一些颜色值，然后生成图片，安装到指定目录罢了。（autotools不也就是干这些的嘛）

**Comment by scratch-er** [comment]
现在这个主题已经使用一个Python脚本自动生成不同的样式，包括不同的颜色、不同的背景。你可以试一试。如果有任何问题，在这里反馈给我，如果没有问题，也跟我说一声，我就发布release并更新到AUR了。
Now it generates different variants with a python script. Please test it and give me feedback.
